docker_repository: pnwbob/mediawiki-ldap
author: pnwbob
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: pnwbob/pnwbob.github.io
tagline: Bob Myers
twitter:
  username: portlandbobm
  card: summary
